# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-08 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youngsphere_sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userminiprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youngsphere_sites.School'),
        ),
    ]
