# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0009_merge_20181113_1517_appsembler'),
        ('sites', '0002_alter_domain_unique'),
        ('youngsphere_sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(max_length=5)),
                ('display_name', models.CharField(max_length=10)),
                ('num_sections', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=144, null=True)),
                ('year', models.IntegerField(default=2020)),
                ('courseno', models.CharField(max_length=50)),
                ('courserun', models.CharField(max_length=30)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youngsphere_sites.Class')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=20, null=True)),
                ('board', models.CharField(blank=True, max_length=20, null=True)),
                ('schoollogo', models.ImageField(blank=True, default=b'school_logo/no-image.jpg', upload_to=b'school_logo')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to='organizations.Organization')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=5)),
                ('description', models.CharField(blank=True, max_length=144, null=True)),
                ('section_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youngsphere_sites.Class')),
            ],
        ),
        migrations.CreateModel(
            name='UserMiniProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('Phone_no', models.CharField(blank=True, max_length=40, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('is_staff', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSectionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youngsphere_sites.Section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youngsphere_sites.Section'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
    ]
