# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-16 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youngsphere_sites', '0002_auto_20190308_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userminiprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mini_user_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
