# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-08 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youngsphere_sites', '0004_auto_20190403_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='page_id',
        ),
        migrations.DeleteModel(
            name='CourseGroup',
        ),
    ]
