# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-08 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youngsphere_sites', '0005_auto_20190508_1016'),
    ]

    operations = [
        
    ]
