# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-13 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youngsphere_sites', '0005_auto_20190131_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativedomain',
            name='site',
        ),
        migrations.AlterField(
            model_name='userminiprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersectionmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AlternativeDomain',
        ),
    ]
