# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-18 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youngsphere_sites', '0006_auto_20190508_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pageid',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        )
    ]
