# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-16 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import openedx.core.djangoapps.xmodule_django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSocialEngagementProgressClassScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('class_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youngsphere_sites.Class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSocialEngagementScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(blank=True, db_index=True, max_length=255)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('num_threads', models.IntegerField(default=0)),
                ('num_thread_followers', models.IntegerField(default=0)),
                ('num_replies', models.IntegerField(default=0)),
                ('num_flagged', models.IntegerField(default=0)),
                ('num_comments', models.IntegerField(default=0)),
                ('num_threads_read', models.IntegerField(default=0)),
                ('num_downvotes', models.IntegerField(default=0)),
                ('num_upvotes', models.IntegerField(default=0)),
                ('num_comments_generated', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSocialEngagementScoreHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(blank=True, db_index=True, max_length=255)),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentsocialengagementscore',
            unique_together=set([('user', 'course_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='studentsocialengagementprogressclassscore',
            unique_together=set([('user', 'class_key')]),
        ),
    ]
