# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-13 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youngsphere_sites', '0006_auto_20190213_1322'),
        ('social_engagement', '0002_studentsocialengagementscore_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSocialEngagementProgressClassScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('class_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youngsphere_sites.Class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentsocialengagementprogressclassscore',
            unique_together=set([('user', 'class_key')]),
        ),
    ]
